[theme]
base = "light"
primaryColor = "#0F62FE"
backgroundColor = "#F6F8FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0B1220"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
